pipelines:
  branches:
    master:
      - step:
          image: ubuntu:latest
          script:
            - curl -fsSL https://bun.sh/install | bash
            - ~/.bun/bin/bun install
            - ~/.bun/bin/bun src/Firekeeper.js
