name: deploy

on:
  push:
    branches: [master]
    paths:
      - "firewalls/*.yml"
      - "firewalls/*.yaml"
      - "!firewalls/firewall.example.yml"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn deploy
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
