name: deploy

on:
  push:
    branches: [main, master]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: curl -fsSL https://bun.sh/install | bash
      - run: ~/.bun/bin/bun install
      - run: ~/.bun/bin/bun run src/Firekeeper.js
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
