name: tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: curl -fsSL https://bun.sh/install | bash
      - run: ~/.bun/bin/bun install
      - run: ~/.bun/bin/bun wiptest
